---
title: "Multiomics vignette"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Installation

First of all we need to install NewWave:

```{r, eval = FALSE}
if(!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("NewWave")
```


```{r}
suppressPackageStartupMessages(
  {library(org.Hs.eg.db)
library(pheatmap)
library(RColorBrewer)
library(graphite)
library(EDASeq)
library(houseOfClipUtility)
library(biocmosclip)
library(MultiAssayExperiment)}
)
```

```{r}
load("../inst/TCGA-OV-hg38-preprocessed-externalSurv.RData")
```


```{r}
survAnnotations <- fup$pfs

expression <- rnaSeq
row.names(expression) <- paste0("ENTREZID:", row.names(expression))
mutation <- mutations$data
row.names(mutation) <- paste0("ENTREZID:", row.names(mutation))
names(metClustValues$eMap) <- paste0("ENTREZID:", row.names(metClustValues$eMap))
row.names(cnv) <- paste0("ENTREZID:", row.names(cnv))

survAnnot <- na.omit(survAnnotations)
patients <- row.names(survAnnot)
patients <- intersect(patients, colnames(expression))
patients <- intersect(patients, colnames(metClustValues$MET_Cancer_Clustered))
patients <- intersect(patients, colnames(mutation))
patients <- intersect(patients, colnames(cnv))
```


```{r}
survAnnot <- survAnnot[patients, , drop = F]
dirname = "vignettes"

expression <- expression[, patients, drop = F]
keep = apply(expression >= 100, 1, any)
expNorm <- betweenLaneNormalization(expression[keep, , drop = F], which = "upper")
pseudoExpNorm <- log2(expNorm + 1)

methylation <- metClustValues
methylation$MET_Cancer_Clustered <- methylation$MET_Cancer_Clustered[, patients, drop = F]

mutation <- mutation[, patients, drop = F]
cnv <- cnv[, patients, drop = F]
```


```{r}
reactome <- pathways("hsapiens", "reactome")
names <- c("PI3K Cascade","Apoptotic cleavage of cellular proteins","RAF-independent MAPK1/3 activation" ,"Mitochondrial protein import")
reactome <- reactome[names]

reactome <- convertIdentifiers(reactome, "entrez")

nodesLength <- sapply(reactome, function(g) {
  length(intersect(graphite::nodes(g), row.names(pseudoExpNorm)))
})

reactSmall <- reactome[nodesLength >= 20 & nodesLength <= 100]
reactHuge <- reactome[nodesLength >= 10]
reactUsed <- reactSmall[c(2,10,20,43)]



reactUsed <-  reactome

```



```{r}
pathHierarchy <- houseOfClipUtility::downloadPathwayRelationFromReactome()
pathHierarchyGraph <- igraph::graph.data.frame(d = pathHierarchy, directed = TRUE)
```


```{r}
multiOmics <- Omics(experiments = ExperimentList(expr = pseudoExpNorm,
                                                 met = methylation$MET_Cancer_Clustered, 
                                                 mut = mutation, cnv = cnv),
                    colData = survAnnot,
                    modelInfo = c("summarizeWithPca", "summarizeInCluster", 
                                  "summarizeToNumberOfEvents", "summarizeToNumberOfDirectionalEvents"),
                    specificArgs = list(pcaArgs = list(name = "exp", shrink = "FALSE",
                                                       method = "sparse", maxPCs = 3),
                                        clusterArgs = list(name = "met",  dict = methylation$eMap,
                                                           max_cluster_number = 3),
                                        countEvent = list(name = "mut", min_prop = 0.05),
                                        cnvAgv = list(name = "cnv", min_prop = 0.05)))

genesToConsider <- row.names(pseudoExpNorm)
```

```{r}

if (file.exists("vignettes/multiOmicsReactome.RData")) {
  load("vignettes/multiOmicsReactome.RData")
} else {
  multiOmicsReactome <- lapply(reactUsed, function(g) {
    print(g@title)  # uncomment this to see the progression along pathways
    set.seed(1234)
    fcl = multiOmicsSurvivalModuleTest(multiOmics, g, useThisGenes = genesToConsider)
    fcl
  })
  }

moduleSummary <- multiPathwayModuleReport(multiOmicsReactome)
moduleSummary


useThisPathways <- unique(moduleSummary$pathway[moduleSummary$pvalue <= 0.05])
sModule <- moduleSummary[moduleSummary$pathway %in% useThisPathways, , drop = T]
```



```{r}
# if (file.exists("perms.RData")) {
#   load("perms.RData")
# } else {
#   perms <- resampling(fullMultiOmics = multiOmics, reactSmall, nperm = 100, 
#                       pathwaySubset = useThisPathways)
#   file = paste0(dirname, "/perms-", as.character(Sys.Date()), ".RData")
#   link = "perms.RData"
#   save(perms, file = file)
#   file.symlink(file, link)
# }


plotModuleReport(multiOmicsReactome[["PI3K Cascade"]], 
                 MOcolors = c(exp = "red", met = "green", cnv = "yellow", mut = "blue"))

additionalA <- survAnnot
additionalA$status[additionalA$status == 1] <- "event"
additionalA$status[additionalA$status == 0] <- "no_event"
additionalA$PFS <- as.factor(additionalA$status)
additionalA$status <- NULL
additionalA$years <- round(additionalA$days/365.24, 0)
additionalA$days <- NULL
plotModuleHeat(multiOmicsReactome$`PI3K Cascade`, 2, 
               paletteNames = c(exp = "red", met = "green", cnv = "yellow"),
               additionalAnnotations = additionalA, 
               additionalPaletteNames = list(PFS = "yellow", years = "teal"),
               sortBy = c("met2k", "expPC1", "PFS", "years"),
               withSampleNames = F)

plotModuleInGraph(multiOmicsReactome$`Mitochondrial protein import`, moduleNumber = 2,
                  legendLabels = c("expr", "methylation", "cnv"),
                  paletteNames = c(exp = "red", met = "green", mut = "blue", cnv = "yellow"))

plotModuleKM(multiOmicsReactome$`PI3K Cascade`, 2, 
             formula = "Surv(days, status) ~ met2k + expPC1", paletteNames = "Paired", risk.table = T, 
             size = 2, inYears = T)

################################################################################
### PATHWAY ANALYSIS

multiOmics@specificArgs$pcaArgs$method = "topological"
multiOmics@specificArgs$pcaArgs$shrink = TRUE
genesToConsider <- row.names(pseudoExpNorm)

if (file.exists("vignettes/multiOmicsFullHuge.RData")) {
  load("vignettes/multiOmicsFullHuge.RData")
} else {
  multiOmicsFullHuge <- lapply(reactHuge, function(g) {
    print(g@title)
    set.seed(1234)
    fcl = multiOmicsSurvivalPathwayTest(multiOmics, g, survAnnot, useThisGenes = genesToConsider)
    fcl
  })
  file = paste0(dirname, "/multiOmicsFullHuge-", as.character(Sys.Date()), ".RData")
  link = "multiOmicsFullHuge.RData"
  save(multiOmicsFullHuge, file = file)
  file.symlink(file, link)
}
```

```{r}
plotMultiPathwayReport(multiOmicsFullHuge, 10,
                       MOcolors = c(exp = "red", mut = "blue", cnv = "yellow", met = "green"))

```


```{r}
multiOmics@specificArgs$pcaArgs$method = "topological"
multiOmics@specificArgs$pcaArgs$shrink = TRUE
genesToConsider <- row.names(pseudoExpNorm)


  
 multiOmicsFullHuge <- lapply(reactUsed, function(g){
    print(g@title)
    set.seed(1234)
    fcl = multiOmicsSurvivalPathwayTest(multiOmics, g, useThisGenes = genesToConsider)
    fcl
})
```


```{r}

plotPathwayHeat(multiOmicsFullHuge$`PI3K Cascade`, sortBy = c("met2k", "expPC1"),
                paletteNames = c(exp = "red", met = "green", mut = "blue", cnv = "yellow"),
                nrowsHeatmaps = 2, withSampleNames = F, fontsize_row = 6)
```

